name: Deploy Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACDnYohliISnhLWO4jdUZ15MTMgzZDgUkUduGBuPlNv3mQAAAJjydPvo8nT7
6AAAAAtzc2gtZWQyNTUxOQAAACDnYohliISnhLWO4jdUZ15MTMgzZDgUkUduGBuPlNv3mQ
AAAEDOBrvQjWkCqLL27IWSEneQIhAs/Tz2hyLCUYr+5g4+FOdiiGWIhKeEtY7iN1RnXkxM
yDNkOBSRR24YG4+U2/eZAAAAD2RlcGxveUBkb3Z0YWxhYgECAwQFBg==
-----END OPENSSH PRIVATE KEY-----
          script: |
            cd /root/Dovtalab

            # 🔹 делаем бэкап данных
            if [ -d data ]; then
              cp -r data /tmp/data_backup || true
            fi

            # 🔹 обновляем проект
            git fetch origin main
            git reset --hard origin/main
            pip install -r requirements.txt

            # 🔹 восстанавливаем данные
            if [ -d /tmp/data_backup ]; then
              cp -r /tmp/data_backup/* data/ || true
            fi

            # 🔹 перезапускаем бота
            sudo systemctl restart tgbot
